package vulkan;

import static vulkan.VulkanCore.gSystemLinker;
import static vulkan.VulkanCore.vkGetInstanceProcAddr;

public final class VkInstance
{
	public final java.lang.foreign.MemorySegment handle;
	public final java.lang.foreign.MemorySegment funcAddress__vkDestroyInstance;
	public final java.lang.invoke.MethodHandle funcHandle__vkDestroyInstance;
	public final java.lang.foreign.MemorySegment funcAddress__vkEnumeratePhysicalDevices;
	public final java.lang.invoke.MethodHandle funcHandle__vkEnumeratePhysicalDevices;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceFeatures;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceFeatures;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceFormatProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceFormatProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceImageFormatProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceImageFormatProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceQueueFamilyProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceQueueFamilyProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceMemoryProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceMemoryProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkCreateDevice;
	public final java.lang.invoke.MethodHandle funcHandle__vkCreateDevice;
	public final java.lang.foreign.MemorySegment funcAddress__vkEnumerateDeviceExtensionProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkEnumerateDeviceExtensionProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkEnumerateDeviceLayerProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkEnumerateDeviceLayerProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceSparseImageFormatProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkEnumeratePhysicalDeviceGroups;
	public final java.lang.invoke.MethodHandle funcHandle__vkEnumeratePhysicalDeviceGroups;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceFeatures2;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceFeatures2;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceProperties2;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceProperties2;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceFormatProperties2;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceFormatProperties2;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceImageFormatProperties2;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceImageFormatProperties2;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceQueueFamilyProperties2;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceQueueFamilyProperties2;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceMemoryProperties2;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceMemoryProperties2;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties2;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceSparseImageFormatProperties2;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceExternalBufferProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceExternalBufferProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceExternalFenceProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceExternalFenceProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceExternalSemaphoreProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceExternalSemaphoreProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceToolProperties;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceToolProperties;
	public final java.lang.foreign.MemorySegment funcAddress__vkDestroySurfaceKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkDestroySurfaceKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceSurfaceSupportKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceSurfaceSupportKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceSurfaceFormatsKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceSurfaceFormatsKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceSurfacePresentModesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceSurfacePresentModesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDevicePresentRectanglesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDevicePresentRectanglesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceDisplayPropertiesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceDisplayPropertiesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceDisplayPlanePropertiesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceDisplayPlanePropertiesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetDisplayPlaneSupportedDisplaysKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetDisplayPlaneSupportedDisplaysKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetDisplayModePropertiesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetDisplayModePropertiesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkCreateDisplayModeKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkCreateDisplayModeKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetDisplayPlaneCapabilitiesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetDisplayPlaneCapabilitiesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkCreateDisplayPlaneSurfaceKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkCreateDisplayPlaneSurfaceKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceVideoCapabilitiesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceVideoCapabilitiesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceVideoFormatPropertiesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceVideoFormatPropertiesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceFeatures2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceFeatures2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceProperties2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceProperties2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceFormatProperties2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceFormatProperties2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceImageFormatProperties2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceImageFormatProperties2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceQueueFamilyProperties2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceQueueFamilyProperties2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceMemoryProperties2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceMemoryProperties2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceSparseImageFormatProperties2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkEnumeratePhysicalDeviceGroupsKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkEnumeratePhysicalDeviceGroupsKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceExternalBufferPropertiesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceExternalBufferPropertiesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceExternalSemaphorePropertiesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceExternalSemaphorePropertiesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceExternalFencePropertiesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceExternalFencePropertiesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceSurfaceCapabilities2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceSurfaceCapabilities2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceSurfaceFormats2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceSurfaceFormats2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceDisplayProperties2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceDisplayProperties2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceDisplayPlaneProperties2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceDisplayPlaneProperties2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetDisplayModeProperties2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetDisplayModeProperties2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetDisplayPlaneCapabilities2KHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetDisplayPlaneCapabilities2KHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceFragmentShadingRatesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceFragmentShadingRatesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR;
	public final java.lang.foreign.MemorySegment funcAddress__vkCreateDebugReportCallbackEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkCreateDebugReportCallbackEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkDestroyDebugReportCallbackEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkDestroyDebugReportCallbackEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkDebugReportMessageEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkDebugReportMessageEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceExternalImageFormatPropertiesNV;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceExternalImageFormatPropertiesNV;
	public final java.lang.foreign.MemorySegment funcAddress__vkReleaseDisplayEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkReleaseDisplayEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceSurfaceCapabilities2EXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceSurfaceCapabilities2EXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkCreateDebugUtilsMessengerEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkCreateDebugUtilsMessengerEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkDestroyDebugUtilsMessengerEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkDestroyDebugUtilsMessengerEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkSubmitDebugUtilsMessageEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkSubmitDebugUtilsMessageEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceMultisamplePropertiesEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceMultisamplePropertiesEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceCalibrateableTimeDomainsEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceCalibrateableTimeDomainsEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceToolPropertiesEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceToolPropertiesEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceCooperativeMatrixPropertiesNV;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceCooperativeMatrixPropertiesNV;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV;
	public final java.lang.foreign.MemorySegment funcAddress__vkCreateHeadlessSurfaceEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkCreateHeadlessSurfaceEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkAcquireDrmDisplayEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkAcquireDrmDisplayEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetDrmDisplayEXT;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetDrmDisplayEXT;
	public final java.lang.foreign.MemorySegment funcAddress__vkGetPhysicalDeviceOpticalFlowImageFormatsNV;
	public final java.lang.invoke.MethodHandle funcHandle__vkGetPhysicalDeviceOpticalFlowImageFormatsNV;

	public VkInstance(java.lang.foreign.MemorySegment handle)
	{
		this.handle = handle;
		try (java.lang.foreign.Arena arena = java.lang.foreign.Arena.ofConfined())
		{
			this.funcAddress__vkDestroyInstance = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkDestroyInstance"));
			this.funcHandle__vkDestroyInstance = this.funcAddress__vkDestroyInstance.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkDestroyInstance, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkEnumeratePhysicalDevices = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkEnumeratePhysicalDevices"));
			this.funcHandle__vkEnumeratePhysicalDevices = this.funcAddress__vkEnumeratePhysicalDevices.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkEnumeratePhysicalDevices, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceFeatures = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceFeatures"));
			this.funcHandle__vkGetPhysicalDeviceFeatures = this.funcAddress__vkGetPhysicalDeviceFeatures.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceFeatures, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceFormatProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceFormatProperties"));
			this.funcHandle__vkGetPhysicalDeviceFormatProperties = this.funcAddress__vkGetPhysicalDeviceFormatProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceFormatProperties, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceImageFormatProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceImageFormatProperties"));
			this.funcHandle__vkGetPhysicalDeviceImageFormatProperties = this.funcAddress__vkGetPhysicalDeviceImageFormatProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceImageFormatProperties, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceProperties"));
			this.funcHandle__vkGetPhysicalDeviceProperties = this.funcAddress__vkGetPhysicalDeviceProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceProperties, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceQueueFamilyProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceQueueFamilyProperties"));
			this.funcHandle__vkGetPhysicalDeviceQueueFamilyProperties = this.funcAddress__vkGetPhysicalDeviceQueueFamilyProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceQueueFamilyProperties, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceMemoryProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceMemoryProperties"));
			this.funcHandle__vkGetPhysicalDeviceMemoryProperties = this.funcAddress__vkGetPhysicalDeviceMemoryProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceMemoryProperties, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkCreateDevice = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkCreateDevice"));
			this.funcHandle__vkCreateDevice = this.funcAddress__vkCreateDevice.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkCreateDevice, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkEnumerateDeviceExtensionProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkEnumerateDeviceExtensionProperties"));
			this.funcHandle__vkEnumerateDeviceExtensionProperties = this.funcAddress__vkEnumerateDeviceExtensionProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkEnumerateDeviceExtensionProperties, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkEnumerateDeviceLayerProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkEnumerateDeviceLayerProperties"));
			this.funcHandle__vkEnumerateDeviceLayerProperties = this.funcAddress__vkEnumerateDeviceLayerProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkEnumerateDeviceLayerProperties, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceSparseImageFormatProperties"));
			this.funcHandle__vkGetPhysicalDeviceSparseImageFormatProperties = this.funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkEnumeratePhysicalDeviceGroups = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkEnumeratePhysicalDeviceGroups"));
			this.funcHandle__vkEnumeratePhysicalDeviceGroups = this.funcAddress__vkEnumeratePhysicalDeviceGroups.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkEnumeratePhysicalDeviceGroups, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceFeatures2 = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceFeatures2"));
			this.funcHandle__vkGetPhysicalDeviceFeatures2 = this.funcAddress__vkGetPhysicalDeviceFeatures2.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceFeatures2, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceProperties2 = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceProperties2"));
			this.funcHandle__vkGetPhysicalDeviceProperties2 = this.funcAddress__vkGetPhysicalDeviceProperties2.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceProperties2, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceFormatProperties2 = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceFormatProperties2"));
			this.funcHandle__vkGetPhysicalDeviceFormatProperties2 = this.funcAddress__vkGetPhysicalDeviceFormatProperties2.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceFormatProperties2, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceImageFormatProperties2 = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceImageFormatProperties2"));
			this.funcHandle__vkGetPhysicalDeviceImageFormatProperties2 = this.funcAddress__vkGetPhysicalDeviceImageFormatProperties2.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceImageFormatProperties2, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceQueueFamilyProperties2 = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceQueueFamilyProperties2"));
			this.funcHandle__vkGetPhysicalDeviceQueueFamilyProperties2 = this.funcAddress__vkGetPhysicalDeviceQueueFamilyProperties2.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceQueueFamilyProperties2, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceMemoryProperties2 = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceMemoryProperties2"));
			this.funcHandle__vkGetPhysicalDeviceMemoryProperties2 = this.funcAddress__vkGetPhysicalDeviceMemoryProperties2.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceMemoryProperties2, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties2 = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceSparseImageFormatProperties2"));
			this.funcHandle__vkGetPhysicalDeviceSparseImageFormatProperties2 = this.funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties2.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties2, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceExternalBufferProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceExternalBufferProperties"));
			this.funcHandle__vkGetPhysicalDeviceExternalBufferProperties = this.funcAddress__vkGetPhysicalDeviceExternalBufferProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceExternalBufferProperties, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceExternalFenceProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceExternalFenceProperties"));
			this.funcHandle__vkGetPhysicalDeviceExternalFenceProperties = this.funcAddress__vkGetPhysicalDeviceExternalFenceProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceExternalFenceProperties, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceExternalSemaphoreProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceExternalSemaphoreProperties"));
			this.funcHandle__vkGetPhysicalDeviceExternalSemaphoreProperties = this.funcAddress__vkGetPhysicalDeviceExternalSemaphoreProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceExternalSemaphoreProperties, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceToolProperties = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceToolProperties"));
			this.funcHandle__vkGetPhysicalDeviceToolProperties = this.funcAddress__vkGetPhysicalDeviceToolProperties.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceToolProperties, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkDestroySurfaceKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkDestroySurfaceKHR"));
			this.funcHandle__vkDestroySurfaceKHR = this.funcAddress__vkDestroySurfaceKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkDestroySurfaceKHR, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceSurfaceSupportKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceSurfaceSupportKHR"));
			this.funcHandle__vkGetPhysicalDeviceSurfaceSupportKHR = this.funcAddress__vkGetPhysicalDeviceSurfaceSupportKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceSurfaceSupportKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceSurfaceCapabilitiesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceSurfaceCapabilitiesKHR"));
			this.funcHandle__vkGetPhysicalDeviceSurfaceCapabilitiesKHR = this.funcAddress__vkGetPhysicalDeviceSurfaceCapabilitiesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceSurfaceCapabilitiesKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceSurfaceFormatsKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceSurfaceFormatsKHR"));
			this.funcHandle__vkGetPhysicalDeviceSurfaceFormatsKHR = this.funcAddress__vkGetPhysicalDeviceSurfaceFormatsKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceSurfaceFormatsKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceSurfacePresentModesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceSurfacePresentModesKHR"));
			this.funcHandle__vkGetPhysicalDeviceSurfacePresentModesKHR = this.funcAddress__vkGetPhysicalDeviceSurfacePresentModesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceSurfacePresentModesKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDevicePresentRectanglesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDevicePresentRectanglesKHR"));
			this.funcHandle__vkGetPhysicalDevicePresentRectanglesKHR = this.funcAddress__vkGetPhysicalDevicePresentRectanglesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDevicePresentRectanglesKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceDisplayPropertiesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceDisplayPropertiesKHR"));
			this.funcHandle__vkGetPhysicalDeviceDisplayPropertiesKHR = this.funcAddress__vkGetPhysicalDeviceDisplayPropertiesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceDisplayPropertiesKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceDisplayPlanePropertiesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceDisplayPlanePropertiesKHR"));
			this.funcHandle__vkGetPhysicalDeviceDisplayPlanePropertiesKHR = this.funcAddress__vkGetPhysicalDeviceDisplayPlanePropertiesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceDisplayPlanePropertiesKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetDisplayPlaneSupportedDisplaysKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetDisplayPlaneSupportedDisplaysKHR"));
			this.funcHandle__vkGetDisplayPlaneSupportedDisplaysKHR = this.funcAddress__vkGetDisplayPlaneSupportedDisplaysKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetDisplayPlaneSupportedDisplaysKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetDisplayModePropertiesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetDisplayModePropertiesKHR"));
			this.funcHandle__vkGetDisplayModePropertiesKHR = this.funcAddress__vkGetDisplayModePropertiesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetDisplayModePropertiesKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkCreateDisplayModeKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkCreateDisplayModeKHR"));
			this.funcHandle__vkCreateDisplayModeKHR = this.funcAddress__vkCreateDisplayModeKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkCreateDisplayModeKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetDisplayPlaneCapabilitiesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetDisplayPlaneCapabilitiesKHR"));
			this.funcHandle__vkGetDisplayPlaneCapabilitiesKHR = this.funcAddress__vkGetDisplayPlaneCapabilitiesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetDisplayPlaneCapabilitiesKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkCreateDisplayPlaneSurfaceKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkCreateDisplayPlaneSurfaceKHR"));
			this.funcHandle__vkCreateDisplayPlaneSurfaceKHR = this.funcAddress__vkCreateDisplayPlaneSurfaceKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkCreateDisplayPlaneSurfaceKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceVideoCapabilitiesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceVideoCapabilitiesKHR"));
			this.funcHandle__vkGetPhysicalDeviceVideoCapabilitiesKHR = this.funcAddress__vkGetPhysicalDeviceVideoCapabilitiesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceVideoCapabilitiesKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceVideoFormatPropertiesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceVideoFormatPropertiesKHR"));
			this.funcHandle__vkGetPhysicalDeviceVideoFormatPropertiesKHR = this.funcAddress__vkGetPhysicalDeviceVideoFormatPropertiesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceVideoFormatPropertiesKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceFeatures2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceFeatures2KHR"));
			this.funcHandle__vkGetPhysicalDeviceFeatures2KHR = this.funcAddress__vkGetPhysicalDeviceFeatures2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceFeatures2KHR, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceProperties2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceProperties2KHR"));
			this.funcHandle__vkGetPhysicalDeviceProperties2KHR = this.funcAddress__vkGetPhysicalDeviceProperties2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceProperties2KHR, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceFormatProperties2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceFormatProperties2KHR"));
			this.funcHandle__vkGetPhysicalDeviceFormatProperties2KHR = this.funcAddress__vkGetPhysicalDeviceFormatProperties2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceFormatProperties2KHR, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceImageFormatProperties2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceImageFormatProperties2KHR"));
			this.funcHandle__vkGetPhysicalDeviceImageFormatProperties2KHR = this.funcAddress__vkGetPhysicalDeviceImageFormatProperties2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceImageFormatProperties2KHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceQueueFamilyProperties2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceQueueFamilyProperties2KHR"));
			this.funcHandle__vkGetPhysicalDeviceQueueFamilyProperties2KHR = this.funcAddress__vkGetPhysicalDeviceQueueFamilyProperties2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceQueueFamilyProperties2KHR, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceMemoryProperties2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceMemoryProperties2KHR"));
			this.funcHandle__vkGetPhysicalDeviceMemoryProperties2KHR = this.funcAddress__vkGetPhysicalDeviceMemoryProperties2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceMemoryProperties2KHR, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceSparseImageFormatProperties2KHR"));
			this.funcHandle__vkGetPhysicalDeviceSparseImageFormatProperties2KHR = this.funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceSparseImageFormatProperties2KHR, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkEnumeratePhysicalDeviceGroupsKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkEnumeratePhysicalDeviceGroupsKHR"));
			this.funcHandle__vkEnumeratePhysicalDeviceGroupsKHR = this.funcAddress__vkEnumeratePhysicalDeviceGroupsKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkEnumeratePhysicalDeviceGroupsKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceExternalBufferPropertiesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceExternalBufferPropertiesKHR"));
			this.funcHandle__vkGetPhysicalDeviceExternalBufferPropertiesKHR = this.funcAddress__vkGetPhysicalDeviceExternalBufferPropertiesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceExternalBufferPropertiesKHR, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceExternalSemaphorePropertiesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceExternalSemaphorePropertiesKHR"));
			this.funcHandle__vkGetPhysicalDeviceExternalSemaphorePropertiesKHR = this.funcAddress__vkGetPhysicalDeviceExternalSemaphorePropertiesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceExternalSemaphorePropertiesKHR, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceExternalFencePropertiesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceExternalFencePropertiesKHR"));
			this.funcHandle__vkGetPhysicalDeviceExternalFencePropertiesKHR = this.funcAddress__vkGetPhysicalDeviceExternalFencePropertiesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceExternalFencePropertiesKHR, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR"));
			this.funcHandle__vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR = this.funcAddress__vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR"));
			this.funcHandle__vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR = this.funcAddress__vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceSurfaceCapabilities2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceSurfaceCapabilities2KHR"));
			this.funcHandle__vkGetPhysicalDeviceSurfaceCapabilities2KHR = this.funcAddress__vkGetPhysicalDeviceSurfaceCapabilities2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceSurfaceCapabilities2KHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceSurfaceFormats2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceSurfaceFormats2KHR"));
			this.funcHandle__vkGetPhysicalDeviceSurfaceFormats2KHR = this.funcAddress__vkGetPhysicalDeviceSurfaceFormats2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceSurfaceFormats2KHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceDisplayProperties2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceDisplayProperties2KHR"));
			this.funcHandle__vkGetPhysicalDeviceDisplayProperties2KHR = this.funcAddress__vkGetPhysicalDeviceDisplayProperties2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceDisplayProperties2KHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceDisplayPlaneProperties2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceDisplayPlaneProperties2KHR"));
			this.funcHandle__vkGetPhysicalDeviceDisplayPlaneProperties2KHR = this.funcAddress__vkGetPhysicalDeviceDisplayPlaneProperties2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceDisplayPlaneProperties2KHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetDisplayModeProperties2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetDisplayModeProperties2KHR"));
			this.funcHandle__vkGetDisplayModeProperties2KHR = this.funcAddress__vkGetDisplayModeProperties2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetDisplayModeProperties2KHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetDisplayPlaneCapabilities2KHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetDisplayPlaneCapabilities2KHR"));
			this.funcHandle__vkGetDisplayPlaneCapabilities2KHR = this.funcAddress__vkGetDisplayPlaneCapabilities2KHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetDisplayPlaneCapabilities2KHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceFragmentShadingRatesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceFragmentShadingRatesKHR"));
			this.funcHandle__vkGetPhysicalDeviceFragmentShadingRatesKHR = this.funcAddress__vkGetPhysicalDeviceFragmentShadingRatesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceFragmentShadingRatesKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR"));
			this.funcHandle__vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR = this.funcAddress__vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkCreateDebugReportCallbackEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkCreateDebugReportCallbackEXT"));
			this.funcHandle__vkCreateDebugReportCallbackEXT = this.funcAddress__vkCreateDebugReportCallbackEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkCreateDebugReportCallbackEXT, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkDestroyDebugReportCallbackEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkDestroyDebugReportCallbackEXT"));
			this.funcHandle__vkDestroyDebugReportCallbackEXT = this.funcAddress__vkDestroyDebugReportCallbackEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkDestroyDebugReportCallbackEXT, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkDebugReportMessageEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkDebugReportMessageEXT"));
			this.funcHandle__vkDebugReportMessageEXT = this.funcAddress__vkDebugReportMessageEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkDebugReportMessageEXT, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceExternalImageFormatPropertiesNV = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceExternalImageFormatPropertiesNV"));
			this.funcHandle__vkGetPhysicalDeviceExternalImageFormatPropertiesNV = this.funcAddress__vkGetPhysicalDeviceExternalImageFormatPropertiesNV.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceExternalImageFormatPropertiesNV, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkReleaseDisplayEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkReleaseDisplayEXT"));
			this.funcHandle__vkReleaseDisplayEXT = this.funcAddress__vkReleaseDisplayEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkReleaseDisplayEXT, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceSurfaceCapabilities2EXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceSurfaceCapabilities2EXT"));
			this.funcHandle__vkGetPhysicalDeviceSurfaceCapabilities2EXT = this.funcAddress__vkGetPhysicalDeviceSurfaceCapabilities2EXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceSurfaceCapabilities2EXT, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkCreateDebugUtilsMessengerEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkCreateDebugUtilsMessengerEXT"));
			this.funcHandle__vkCreateDebugUtilsMessengerEXT = this.funcAddress__vkCreateDebugUtilsMessengerEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkCreateDebugUtilsMessengerEXT, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkDestroyDebugUtilsMessengerEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkDestroyDebugUtilsMessengerEXT"));
			this.funcHandle__vkDestroyDebugUtilsMessengerEXT = this.funcAddress__vkDestroyDebugUtilsMessengerEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkDestroyDebugUtilsMessengerEXT, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkSubmitDebugUtilsMessageEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkSubmitDebugUtilsMessageEXT"));
			this.funcHandle__vkSubmitDebugUtilsMessageEXT = this.funcAddress__vkSubmitDebugUtilsMessageEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkSubmitDebugUtilsMessageEXT, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceMultisamplePropertiesEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceMultisamplePropertiesEXT"));
			this.funcHandle__vkGetPhysicalDeviceMultisamplePropertiesEXT = this.funcAddress__vkGetPhysicalDeviceMultisamplePropertiesEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceMultisamplePropertiesEXT, java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceCalibrateableTimeDomainsEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceCalibrateableTimeDomainsEXT"));
			this.funcHandle__vkGetPhysicalDeviceCalibrateableTimeDomainsEXT = this.funcAddress__vkGetPhysicalDeviceCalibrateableTimeDomainsEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceCalibrateableTimeDomainsEXT, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceToolPropertiesEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceToolPropertiesEXT"));
			this.funcHandle__vkGetPhysicalDeviceToolPropertiesEXT = this.funcAddress__vkGetPhysicalDeviceToolPropertiesEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceToolPropertiesEXT, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceCooperativeMatrixPropertiesNV = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceCooperativeMatrixPropertiesNV"));
			this.funcHandle__vkGetPhysicalDeviceCooperativeMatrixPropertiesNV = this.funcAddress__vkGetPhysicalDeviceCooperativeMatrixPropertiesNV.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceCooperativeMatrixPropertiesNV, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV"));
			this.funcHandle__vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV = this.funcAddress__vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkCreateHeadlessSurfaceEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkCreateHeadlessSurfaceEXT"));
			this.funcHandle__vkCreateHeadlessSurfaceEXT = this.funcAddress__vkCreateHeadlessSurfaceEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkCreateHeadlessSurfaceEXT, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkAcquireDrmDisplayEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkAcquireDrmDisplayEXT"));
			this.funcHandle__vkAcquireDrmDisplayEXT = this.funcAddress__vkAcquireDrmDisplayEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkAcquireDrmDisplayEXT, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetDrmDisplayEXT = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetDrmDisplayEXT"));
			this.funcHandle__vkGetDrmDisplayEXT = this.funcAddress__vkGetDrmDisplayEXT.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetDrmDisplayEXT, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS));
			this.funcAddress__vkGetPhysicalDeviceOpticalFlowImageFormatsNV = vkGetInstanceProcAddr(this.handle, arena.allocateUtf8String("vkGetPhysicalDeviceOpticalFlowImageFormatsNV"));
			this.funcHandle__vkGetPhysicalDeviceOpticalFlowImageFormatsNV = this.funcAddress__vkGetPhysicalDeviceOpticalFlowImageFormatsNV.equals(java.lang.foreign.MemorySegment.NULL) ? null : gSystemLinker.downcallHandle(this.funcAddress__vkGetPhysicalDeviceOpticalFlowImageFormatsNV, java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS, java.lang.foreign.ValueLayout.ADDRESS));
		}
	}

	public java.lang.foreign.MemorySegment handle() {return this.handle;}
}
